### ISSUE TITLE
启动时空指针

### ISSUE THREAD

**Issue by Jiezhi** [simplezhli/ChangeTabLayout#2]
`  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zl.changetablayout/com.zl.changetablayout.MainActivity}: java.lang.NullPointerException
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2473)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
                                                                            at android.app.ActivityThread.access$1200(ActivityThread.java:165)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1387)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5689)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                         Caused by: java.lang.NullPointerException
                                                                            at android.content.res.XmlBlock.nativeGetStyleAttribute(Native Method)
                                                                            at android.content.res.XmlBlock.access$1400(XmlBlock.java:34)
                                                                            at android.content.res.XmlBlock$Parser.getStyleAttribute(XmlBlock.java:440)
                                                                            at android.widget.TextView.<init>(TextView.java:667)
                                                                            at android.widget.TextView.<init>(TextView.java:659)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                            at com.github.zl.changetablayout.ChangeTextView.<init>(ChangeTextView.java:0)
                                                                            at com.github.zl.changetablayout.ChangeTextView.<init>(ChangeTextView.java:0)
                                                                            at com.github.zl.changetablayout.ChangeTabLayout.createTabView(ChangeTabLayout.java:204)
                                                                            at com.github.zl.changetablayout.ChangeTabLayout.populateTabStrip(ChangeTabLayout.java:152)
                                                                            at com.github.zl.changetablayout.ChangeTabLayout.setViewPager(ChangeTabLayout.java:132)
                                                                            at com.zl.changetablayout.MainActivity.onCreate(MainActivity.java:86)
                                                                            at android.app.Activity.performCreate(Activity.java:6102)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2420)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535) 
                                                                            at android.app.ActivityThread.access$1200(ActivityThread.java:165) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1387) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5689) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) `

**Comment by simplezhli** [comment]
麻烦提供一下你的机型与版本。

**Comment by simplezhli** [comment]
我看报错最终是进入TextView，我索性将继承AppCompatTextView改为View重新进行实现。你可以先进入origin分支再试试，如果好了的话。我在合并到master上。

**Comment by Jiezhi** [comment]
设备是 Huawei Pad FDR-A03L android 5.1.1 API 22

origin分支可以正常运行，感谢
